[project]
name = "update-bot"
version = "0.1.0"
description = "Proof of concept for simple workflow to bump uv versions"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.1",
]
